# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MealPrepr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MealPrepr

  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  #pod 'Firebase/Firestore'
  #pod 'FirebaseFirestoreSwift'
  pod 'FBSDKLoginKit'

  target 'MealPreprTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MealPreprUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
