# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PickupGames' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PickupGames

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'FBSDKLoginKit'
  
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'PickupGamesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PickupGamesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
